language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
# command to run tests
script: touch ".nocompile" && ./unit_tests/bmrb_test.py && rm .nocompile && ./unit_tests/bmrb_test.py
