dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: ignore
# command to run tests
script: touch "pynmrstar/.nocompile" && python3 -m pynmrstar.unit_tests && rm pynmrstar/.nocompile && python3 -m pynmrstar.unit_tests
