language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
# command to run tests
script: touch ".nocompile" && ./pynmrstar.py && rm .nocompile && ./pynmrstar.py
