dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
# command to run tests
script: touch "pynmrstar/.nocompile" && ./unit_tests/bmrb_test.py && rm pynmrstar/.nocompile && ./unit_tests/bmrb_test.py
