name: Test the python package

on: [push, pull_request]

jobs:
  run_tests:
    name: Test library on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        python: [ 36, 37, 38, 39 ]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --recursive
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt
      - name: Run tests
        run: |
          touch "pynmrstar/.nocompile"
          python3 -m pynmrstar.unit_tests
          rm pynmrstar/.nocompile
          python3 -m pynmrstar.unit_tests