name: Run self test

on:
  push:
    branches:
      - v3-dev
  pull_request:
    branches:
      - v3

jobs:
  run_tests:
    name: Testing on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        python-version: [ 3.6, 3.7, 3.8, 3.9, "pypy3" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies for pypy3
        if: ${{ matrix.python-version == 'pypy3' }}
        run: pypy3 -m pip install -r requirements.txt
      - name: Install dependencies for CPython
        if: ${{ matrix.python-version != 'pypy3' }}
        run: python3 -m pip install -r requirements.txt
      - name: Build c extension for pypy3
        if: ${{ matrix.python-version == 'pypy3' }}
        run: pypy3 -m pip install ./c
      - name: Build c extension for Cpython
        if: ${{ matrix.python-version != 'pypy3' }}
        run: python3 -m pip install ./c
      #- name: Launch interactive debug if build fails
#        uses: mxschmitt/action-tmate@v3
      - name: Run tests
        run: python3 -m pynmrstar.unit_tests